title: Nabil Ahda Murtadha
discription: Candango de pais indonésios, formado em economia, apaixonado pela ciência de dados
logo: "https://pbs.twimg.com/profile_images/1265360977849135104/XzibyheD_400x400.jpg"
theme: jekyll-theme-minimal
