title: Nabil Ahda Murtadha
logo: "https://pbs.twimg.com/profile_images/1265360977849135104/XzibyheD_400x400.jpg"
description: Candango, filho de imigrantes indonésios, economista apaixonado pela ciência de dados e por temas sociais.
theme: jekyll-theme-minimal
