title: Nabil Ahda Murtadha
logo: "https://pbs.twimg.com/profile_images/1265360977849135104/XzibyheD_400x400.jpg"
discription: Candango, filho de imigrantes indonésios, formado em economia na UnB, apaixonado pela ciência de dados e por temas sociais.
theme: jekyll-theme-minimal
